version: '2.1'
services:
  postgres:
    image: postgres:10-alpine
    environment:
    - "POSTGRES_USER=pg"
    - "POSTGRES_PASSWORD=pg"
    - "POSTGRES_DB=pg"
    ports:
    - 5432
  liquibase-refactoring-column-name:
    container_name: liquibase-refactoring-column-name
    image: liquibaserefactoringcolumnname:latest
    ports:
    - 8080:8080
    environment:
    - "--spring.datasource.url=jdbc:postgresql://postgres:5432/pg"
